// Admin-specific actions — SSH, sudo, systemctl, remote file copy, config editing
export default [
  {
    type: 'ssh-exec',
    title: 'SSH Execute Command',
    desc: 'Run a command remotely via SSH → result (stdout)',
    icon: 'terminal',
    color: '#7C3AED',
    outputType: 'text',
    defaults: {
      host: '',
      user: 'root',
      port: '22',
      command: 'whoami',
      timeout: '30',
    },
    params: [
      { name: 'host', label: 'Hostname or IP', kind: 'text', placeholder: '192.168.1.1', acceptsVars: true },
      { name: 'user', label: 'Username', kind: 'text', placeholder: 'root', acceptsVars: true },
      { name: 'port', label: 'Port', kind: 'text', placeholder: '22', acceptsVars: true },
      { name: 'command', label: 'Command to execute', kind: 'textarea', placeholder: 'systemctl status nginx', acceptsVars: true },
      { name: 'timeout', label: 'Timeout (seconds)', kind: 'number', placeholder: '30' },
    ],
  },
  {
    type: 'scp-copy',
    title: 'SCP Copy File',
    desc: 'Copy file to/from remote via SCP',
    icon: 'copy',
    color: '#EC4899',
    outputType: 'file',
    defaults: {
      source: '',
      destination: '',
      direction: 'to_remote',
    },
    params: [
      { name: 'source', label: 'Source path (local or user@host:/path)', kind: 'text', placeholder: '/home/user/file.txt', acceptsVars: true },
      { name: 'destination', label: 'Destination path', kind: 'text', placeholder: 'root@192.168.1.1:/tmp/', acceptsVars: true },
      {
        name: 'direction',
        label: 'Direction',
        kind: 'select',
        options: [
          { value: 'to_remote', label: 'Local → Remote' },
          { value: 'from_remote', label: 'Remote → Local' },
        ],
      },
    ],
  },
  {
    type: 'systemctl-control',
    title: 'Systemctl Control',
    desc: 'Start, stop, restart, or check status of a systemd service',
    icon: 'power',
    color: '#06B6D4',
    outputType: 'text',
    defaults: {
      service: 'nginx',
      action: 'status',
    },
    params: [
      { name: 'service', label: 'Service name', kind: 'text', placeholder: 'nginx', acceptsVars: true },
      {
        name: 'action',
        label: 'Action',
        kind: 'select',
        options: [
          { value: 'status', label: 'Status' },
          { value: 'start', label: 'Start' },
          { value: 'stop', label: 'Stop' },
          { value: 'restart', label: 'Restart' },
          { value: 'reload', label: 'Reload' },
          { value: 'enable', label: 'Enable on Boot' },
          { value: 'disable', label: 'Disable on Boot' },
        ],
      },
    ],
  },
  {
    type: 'sudo-exec',
    title: 'Sudo Execute',
    desc: 'Run a command with elevated privileges (will prompt for password if needed)',
    icon: 'shield',
    color: '#F59E0B',
    outputType: 'text',
    defaults: {
      command: 'systemctl status',
    },
    params: [
      { name: 'command', label: 'Command to run as root', kind: 'textarea', placeholder: 'systemctl restart apache2', acceptsVars: true },
    ],
  },
  {
    type: 'file-permissions',
    title: 'Change File Permissions',
    desc: 'Modify file permissions (chmod) and ownership (chown)',
    icon: 'lock',
    color: '#8B5CF6',
    outputType: 'text',
    defaults: {
      path: '',
      mode: '755',
      owner: '',
      recursive: false,
    },
    params: [
      { name: 'path', label: 'File/Directory path', kind: 'text', placeholder: '/path/to/file', acceptsVars: true },
      { name: 'mode', label: 'Permissions (octal)', kind: 'text', placeholder: '755' },
      { name: 'owner', label: 'Owner:Group (optional)', kind: 'text', placeholder: 'www-data:www-data', acceptsVars: true },
      {
        name: 'recursive',
        label: 'Recursive (-R)',
        kind: 'select',
        options: [
          { value: false, label: 'No' },
          { value: true, label: 'Yes' },
        ],
      },
    ],
  },
  {
    type: 'cron-schedule',
    title: 'Create Cron Job',
    desc: 'Add a task to the system crontab for scheduled execution',
    icon: 'calendar-clock',
    color: '#14B8A6',
    outputType: 'text',
    defaults: {
      schedule: '0 2 * * *',
      command: '/usr/local/bin/backup.sh',
      user: 'root',
    },
    params: [
      { name: 'schedule', label: 'Cron schedule', kind: 'text', placeholder: '0 2 * * * (daily at 2am)', acceptsVars: true },
      { name: 'command', label: 'Command to execute', kind: 'textarea', placeholder: '/usr/local/bin/backup.sh', acceptsVars: true },
      { name: 'user', label: 'Run as user', kind: 'text', placeholder: 'root', acceptsVars: true },
    ],
  },
  {
    type: 'check-port-open',
    title: 'Check Port Status',
    desc: 'Test if a port is open on local or remote machine',
    icon: 'network',
    color: '#10B981',
    outputType: 'text',
    defaults: {
      host: 'localhost',
      port: '80',
      protocol: 'tcp',
    },
    params: [
      { name: 'host', label: 'Hostname/IP', kind: 'text', placeholder: 'localhost', acceptsVars: true },
      { name: 'port', label: 'Port number', kind: 'number', placeholder: '80', acceptsVars: true },
      {
        name: 'protocol',
        label: 'Protocol',
        kind: 'select',
        options: [
          { value: 'tcp', label: 'TCP' },
          { value: 'udp', label: 'UDP' },
        ],
      },
    ],
  },
  {
    type: 'app-launch',
    title: 'Launch Application',
    desc: 'Launch an application, command, or file (desktop Linux)',
    icon: 'rocket',
    color: '#F97316',
    outputType: null,
    defaults: { target: 'gedit' },
    params: [
      { name: 'target', label: 'App/command/file path', kind: 'text', placeholder: 'gedit', acceptsVars: true },
    ],
  },
  {
    type: 'notify-desktop',
    title: 'Desktop Notification',
    desc: 'Show a desktop notification (uses notify-send on Linux)',
    icon: 'bell-ring',
    color: '#F43F5E',
    outputType: null,
    defaults: {
      title: 'Notification',
      body: '{{result}}',
      urgency: 'normal',
    },
    params: [
      { name: 'title', label: 'Title', kind: 'text', placeholder: 'Notification', acceptsVars: true },
      { name: 'body', label: 'Message', kind: 'textarea', placeholder: '{{result}}', acceptsVars: true },
      {
        name: 'urgency',
        label: 'Urgency',
        kind: 'select',
        options: [
          { value: 'low', label: 'Low' },
          { value: 'normal', label: 'Normal' },
          { value: 'critical', label: 'Critical' },
        ],
      },
    ],
  },
]
