// Office actions — zip, compress, docx, xlsx, pptx, pdf conversions
export default [
  {
    type: 'zip-extract',
    title: 'Extract ZIP',
    desc: 'Extract a ZIP archive to a folder',
    icon: 'archive-restore',
    color: '#FF9F0A',
    outputType: 'file',
    defaults: { zipPath: '{{result}}', destDir: '' },
    params: [
      { name: 'zipPath', label: 'ZIP file path', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
      { name: 'destDir', label: 'Destination folder (empty = same as zip)', kind: 'text', placeholder: '/home/user/Documents/', acceptsVars: true },
    ],
  },
  {
    type: 'folder-compress',
    title: 'Compress to ZIP',
    desc: 'Compress a folder or file into a ZIP archive',
    icon: 'archive',
    color: '#FF9F0A',
    outputType: 'file',
    defaults: { sourcePath: '{{result}}', zipPath: '' },
    params: [
      { name: 'sourcePath', label: 'Folder or file to compress', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
      { name: 'zipPath', label: 'Output ZIP path (empty = auto)', kind: 'text', placeholder: '/home/user/archive.zip', acceptsVars: true },
    ],
  },
  {
    type: 'create-docx',
    title: 'Create Word Document',
    desc: 'Generate a .docx file from text or markdown content',
    icon: 'file-text',
    color: '#2B579A',
    outputType: 'file',
    defaults: { content: '{{result}}', outputPath: '', title: '' },
    params: [
      { name: 'content', label: 'Content (text or markdown)', kind: 'textarea', placeholder: '{{result}}', acceptsVars: true },
      { name: 'title', label: 'Document title (optional)', kind: 'text', placeholder: 'My Document', acceptsVars: true },
      { name: 'outputPath', label: 'Output path (empty = ~/Documents/)', kind: 'text', placeholder: '/home/user/doc.docx', acceptsVars: true },
    ],
  },
  {
    type: 'create-xlsx',
    title: 'Create Excel Spreadsheet',
    desc: 'Generate a .xlsx file from JSON array or CSV text',
    icon: 'table',
    color: '#217346',
    outputType: 'file',
    defaults: { data: '{{result}}', outputPath: '', sheetName: 'Sheet1' },
    params: [
      { name: 'data', label: 'Data — JSON array of objects or CSV text', kind: 'textarea', placeholder: '[{"Name":"Alice","Score":95}]', acceptsVars: true },
      { name: 'sheetName', label: 'Sheet name', kind: 'text', placeholder: 'Sheet1', acceptsVars: true },
      { name: 'outputPath', label: 'Output path (empty = ~/Documents/)', kind: 'text', placeholder: '/home/user/data.xlsx', acceptsVars: true },
    ],
  },
  {
    type: 'create-pptx',
    title: 'Create PowerPoint',
    desc: 'Generate a .pptx presentation from a JSON slide outline',
    icon: 'presentation',
    color: '#D04423',
    outputType: 'file',
    defaults: { slides: '{{result}}', outputPath: '', title: '' },
    params: [
      {
        name: 'slides',
        label: 'Slides — JSON array [{title, content, notes?}]',
        kind: 'textarea',
        placeholder: '[{"title":"Slide 1","content":"Body text"},{"title":"Slide 2","content":"More text"}]',
        acceptsVars: true,
      },
      { name: 'title', label: 'Presentation title', kind: 'text', placeholder: 'My Presentation', acceptsVars: true },
      { name: 'outputPath', label: 'Output path (empty = ~/Documents/)', kind: 'text', placeholder: '/home/user/slides.pptx', acceptsVars: true },
    ],
  },
  {
    type: 'text-to-pdf',
    title: 'Text / Markdown to PDF',
    desc: 'Convert plain text or markdown content to a PDF file via pandoc',
    icon: 'file-down',
    color: '#FF453A',
    outputType: 'file',
    defaults: { content: '{{result}}', outputPath: '', fontSize: '12' },
    params: [
      { name: 'content', label: 'Text or markdown content', kind: 'textarea', placeholder: '{{result}}', acceptsVars: true },
      { name: 'outputPath', label: 'Output PDF path (empty = auto)', kind: 'text', placeholder: '/home/user/output.pdf', acceptsVars: true },
      { name: 'fontSize', label: 'Font size (pt)', kind: 'number', placeholder: '12', acceptsVars: false },
    ],
  },
  {
    type: 'html-to-pdf',
    title: 'HTML to PDF',
    desc: 'Convert an HTML file or HTML string to PDF via wkhtmltopdf',
    icon: 'file-code',
    color: '#FF453A',
    outputType: 'file',
    defaults: { input: '{{result}}', outputPath: '' },
    params: [
      { name: 'input', label: 'HTML file path or HTML string', kind: 'textarea', placeholder: '{{result}}', acceptsVars: true },
      { name: 'outputPath', label: 'Output PDF path (empty = auto)', kind: 'text', placeholder: '/home/user/output.pdf', acceptsVars: true },
    ],
  },
  {
    type: 'website-to-pdf',
    title: 'Website to PDF',
    desc: 'Save a web page as a PDF file via wkhtmltopdf',
    icon: 'globe',
    color: '#FF453A',
    outputType: 'file',
    defaults: { url: '{{result}}', outputPath: '' },
    params: [
      { name: 'url', label: 'URL', kind: 'text', placeholder: 'https://example.com', acceptsVars: true },
      { name: 'outputPath', label: 'Output PDF path (empty = auto)', kind: 'text', placeholder: '/home/user/page.pdf', acceptsVars: true },
    ],
  },
]
