// System (Linux/desktop) actions — shell, files, git, variables, screenshot, chart
export default [
  {
    type: 'shell',
    title: 'Run Shell Command',
    desc: 'Execute a shell command → result (stdout)',
    icon: 'terminal',
    color: '#FF9F0A',
    outputType: 'text',
    defaults: { command: 'echo {{result}}' },
    params: [
      {
        name: 'command',
        label: 'Shell command',
        kind: 'textarea',
        placeholder: 'echo {{result}}',
        acceptsVars: true,
      },
    ],
  },
  {
    type: 'image-clean',
    title: 'Clean Image',
    desc: 'Remove all metadata and subtly alter image to break AI marks/watermarks',
    icon: 'shield-check',
    color: '#32D74B',
    outputType: 'file',
    defaults: { filePath: '{{result}}' },
    params: [
      { name: 'filePath', label: 'Image File Path', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
    ],
  },
  {
    type: 'set-var',
    title: 'Save to Variable',
    desc: 'Store result under a named variable for later steps',
    icon: 'save',
    color: '#64D2FF',
    outputType: null,
    defaults: { varName: 'myVar' },
    params: [
      { name: 'varName', label: 'Variable name', kind: 'text', placeholder: 'myVar' },
    ],
  },
  {
    type: 'screenshot-capture',
    title: 'Take Screenshot',
    desc: 'Capture the primary screen → result (filePath)',
    icon: 'camera',
    color: '#FF375F',
    outputType: 'image',
    defaults: {},
    params: [],
  },
  {
    type: 'file-rename',
    title: 'Rename File',
    desc: 'Change the name of a file',
    icon: 'edit-3',
    color: '#0A84FF',
    outputType: 'file',
    defaults: { oldPath: '{{result}}', newPath: '' },
    params: [
      { name: 'oldPath', label: 'Current path', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
      { name: 'newPath', label: 'New path / name', kind: 'text', placeholder: '/path/to/newname.txt', acceptsVars: true },
    ],
  },
  {
    type: 'file-move',
    title: 'Move File',
    desc: 'Move a file to a new location',
    icon: 'move',
    color: '#0A84FF',
    outputType: 'file',
    defaults: { src: '{{result}}', dest: '' },
    params: [
      { name: 'src', label: 'Source path', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
      { name: 'dest', label: 'Destination path', kind: 'text', placeholder: '/home/user/Desktop/', acceptsVars: true },
    ],
  },
  {
    type: 'file-delete',
    title: 'Delete File',
    desc: 'Permanently remove a file',
    icon: 'trash-2',
    color: '#FF453A',
    outputType: null,
    defaults: { path: '{{result}}' },
    params: [
      { name: 'path', label: 'File path', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
    ],
  },
  {
    type: 'git-clone',
    title: 'Git Clone',
    desc: 'Clone a git repository into a folder',
    icon: 'github',
    color: '#24292e',
    outputType: 'file',
    defaults: { url: '', targetDir: '{{result}}' },
    params: [
      { name: 'url', label: 'Repository URL', kind: 'text', placeholder: 'https://github.com/user/repo.git', acceptsVars: true },
      { name: 'targetDir', label: 'Target Folder', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
    ],
  },
  {
    type: 'git-init',
    title: 'Git Init',
    desc: 'Initialize a new git repository and add origin',
    icon: 'git-branch',
    color: '#F05032',
    outputType: 'file',
    defaults: { folder: '{{result}}', originUrl: '' },
    params: [
      { name: 'folder', label: 'Folder Path', kind: 'text', placeholder: '{{result}}', acceptsVars: true },
      { name: 'originUrl', label: 'Remote Origin URL (optional)', kind: 'text', placeholder: 'https://github.com/user/repo.git', acceptsVars: true },
    ],
  },
  {
    type: 'plot-chart',
    title: 'Plot Chart',
    desc: 'Generate a chart from JSON data',
    icon: 'bar-chart',
    color: '#32D74B',
    outputType: 'chart',
    defaults: {
      data: '{{result}}',
      chartType: 'bar',
      title: 'My Chart',
      xAxis: 'label',
      yAxis: 'value',
    },
    params: [
      { name: 'data', label: 'JSON Data (array or object)', kind: 'textarea', placeholder: '[{"label":"A", "value":10}, {"label":"B", "value":20}]', acceptsVars: true },
      {
        name: 'chartType',
        label: 'Chart Type',
        kind: 'select',
        options: [
          { value: 'bar', label: 'Bar' },
          { value: 'line', label: 'Line' },
          { value: 'pie', label: 'Pie' },
          { value: 'doughnut', label: 'Doughnut' },
          { value: 'polarArea', label: 'Polar Area' },
          { value: 'radar', label: 'Radar' },
        ],
      },
      { name: 'title', label: 'Chart Title', kind: 'text', placeholder: 'My Chart', acceptsVars: true },
      { name: 'xAxis', label: 'Key for Labels (X-Axis)', kind: 'text', placeholder: 'name' },
    ],
  },
]
