// Media shortcuts (ids 21–23, 25, 36, 41–42, 46, 55, 82–86)
import { makeStep, getActionDef } from '../actions/index.js'

function step(type, overrides = {}) {
  const def = getActionDef(type)
  if (!def) throw new Error(`defaultShortcuts: unknown action type "${type}"`)
  return { ...makeStep(def), ...overrides }
}

export default [
  {
    id: 21,
    name: 'Describe Image',
    icon: 'eye',
    color: 'bg-indigo',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Image', buttonLabel: 'Select Image' }),
      step('image-vision', {
        title: 'Analyze Image',
        filePath: '{{result}}',
        prompt: 'Describe this image in detail and extract any visible text into a formatted list.',
      }),
      step('show-result', { title: 'Image Analysis', label: 'Image Details' }),
    ],
  },
  {
    id: 22,
    name: 'Transcribe Audio',
    icon: 'mic',
    color: 'bg-orange',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Audio File', buttonLabel: 'Select Audio' }),
      step('asr', { title: 'Transcribe', filePath: '{{result}}' }),
      step('clipboard-write', { title: 'Copy Transcription' }),
      step('show-result', { title: 'Transcription', label: 'Transcription' }),
    ],
  },
  {
    id: 23,
    name: 'Generate Artwork',
    icon: 'palette',
    color: 'bg-pink',
    category: 'media',
    favorite: false,
    steps: [
      step('user-input', {
        title: 'Art Prompt',
        label: 'Image Prompt',
        placeholder: 'A futuristic city in the style of Moebius',
      }),
      step('image-gen', { title: 'Generate Image', prompt: '{{result}}' }),
      step('show-result', { title: 'Generated Image', label: 'AI Artwork' }),
    ],
  },
  {
    id: 25,
    name: 'Voice Memo',
    icon: 'mic-2',
    color: 'bg-red',
    category: 'media',
    favorite: true,
    steps: [
      step('audio-record', { title: 'Record Voice', duration: 60 }),
      step('asr', { title: 'Transcribe', filePath: '{{result}}' }),
      step('show-result', { title: 'Transcription', label: 'Voice Note' }),
    ],
  },
  {
    id: 36,
    name: 'Quick Screenshot',
    icon: 'camera',
    color: 'bg-red',
    category: 'media',
    favorite: true,
    steps: [
      step('screenshot-capture', { title: 'Capture Screen' }),
      step('show-result', { title: 'Captured', label: 'Screenshot' }),
    ],
  },
  {
    id: 41,
    name: 'YouTube Downloader',
    icon: 'youtube',
    color: 'bg-red',
    category: 'media',
    favorite: true,
    steps: [
      step('user-input', { title: 'YouTube URL', label: 'Paste YouTube URL:', placeholder: 'https://youtube.com/watch?v=...' }),
      step('set-var', { varName: 'ytUrl' }),
      step('folder-picker', { title: 'Save Folder', buttonLabel: 'Download Here' }),
      step('youtube-download', { title: 'Downloading...', url: '{{vars.ytUrl}}', outputDir: '{{result}}', format: 'mp4' }),
      step('notification', { title: 'Download Complete', body: 'Video saved to {{result}}' }),
      step('reveal-file', { title: 'Show Video', path: '{{result}}' }),
    ],
  },
  {
    id: 42,
    name: 'YouTube to MP3',
    icon: 'music',
    color: 'bg-orange',
    category: 'media',
    favorite: false,
    steps: [
      step('clipboard-read', { title: 'Get URL' }),
      step('confirm-dialog', { title: 'Download Audio?', message: 'Download MP3 from {{result}}?' }),
      step('set-var', { varName: 'ytUrl' }),
      step('folder-picker', { title: 'Save Folder', buttonLabel: 'Save MP3 Here' }),
      step('youtube-download', { title: 'Extracting Audio...', url: '{{vars.ytUrl}}', outputDir: '{{result}}', format: 'mp3' }),
      step('notification', { title: 'MP3 Ready', body: 'Audio extracted successfully' }),
    ],
  },
  {
    id: 46,
    name: 'AI Filename Pro',
    icon: 'file-edit',
    color: 'bg-indigo',
    category: 'ai',
    favorite: false,
    steps: [
      step('user-input', { title: 'Context', label: 'What is this file about?', placeholder: 'Meeting notes from today about the new project' }),
      step('ai-prompt', {
        title: 'Optimizing Name...',
        prompt: 'Generate a clean, SEO-friendly, kebab-case filename (no extension) for this context: {{result}}',
        systemPrompt: 'Output ONLY the slugified filename, no preamble or quotes.',
      }),
      step('filename-generate', { title: 'Cleaning...', text: '{{result}}' }),
      step('show-result', { title: 'Optimized Name', label: 'Perfect Filename' }),
    ],
  },
  {
    id: 55,
    name: 'Image to WEBP',
    icon: 'image',
    color: 'bg-green',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Select Image' }),
      step('set-var', { varName: 'imgPath' }),
      step('filename-generate', { title: 'Naming...', text: '{{result}}', extension: 'webp' }),
      step('shell', { title: 'Converting...', command: 'magick "{{vars.imgPath}}" "{{result}}"' }),
      step('notification', { title: 'Converted', body: 'Image saved as WEBP' }),
    ],
  },
  {
    id: 82,
    name: 'Tag MP3',
    icon: 'tag',
    color: 'bg-orange',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick MP3', buttonLabel: 'Select MP3' }),
      step('set-var', { title: 'Save Path', varName: 'mp3Path' }),
      step('user-input', { title: 'Title', label: 'Song Title:', placeholder: 'My Awesome Song' }),
      step('set-var', { title: 'Save Title', varName: 'mTitle' }),
      step('user-input', { title: 'Artist', label: 'Artist:', placeholder: 'The Shortcuts' }),
      step('set-var', { title: 'Save Artist', varName: 'mArtist' }),
      step('media-metadata-tag', {
        filePath: '{{vars.mp3Path}}',
        title: '{{vars.mTitle}}',
        artist: '{{vars.mArtist}}',
      }),
      step('notification', { title: 'MP3 Tagged', body: 'Metadata applied to {{vars.mTitle}}' }),
    ],
  },
  {
    id: 83,
    name: 'Audio to Video Poster',
    icon: 'film',
    color: 'bg-indigo',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Audio', buttonLabel: 'Select Audio' }),
      step('set-var', { title: 'Save Audio Path', varName: 'audioPath' }),
      step('file-picker', { title: 'Pick Poster Image', buttonLabel: 'Select Image' }),
      step('set-var', { title: 'Save Image Path', varName: 'imagePath' }),
      step('media-merge-poster', {
        audioPath: '{{vars.audioPath}}',
        imagePath: '{{vars.imagePath}}',
      }),
      step('show-result', { title: 'Video Created', label: 'Output Video' }),
    ],
  },
  {
    id: 84,
    name: 'Extract MP3 from Video',
    icon: 'music',
    color: 'bg-green',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Video', buttonLabel: 'Select Video' }),
      step('media-extract-audio', { format: 'mp3' }),
      step('notification', { title: 'Audio Extracted', body: 'Saved as .mp3 next to video' }),
      step('show-result', { title: 'Audio File', label: 'Extracted Audio' }),
    ],
  },
  {
    id: 85,
    name: 'Convert Video',
    icon: 'refresh-cw',
    color: 'bg-blue',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Video', buttonLabel: 'Select Video' }),
      step('set-var', { title: 'Save Video Path', varName: 'videoPath' }),
      step('user-input', {
        title: 'Target Format',
        label: 'Enter format (mp4, mkv, webm):',
        prefill: 'mp4',
      }),
      step('media-convert', { inputPath: '{{vars.videoPath}}', format: '{{result}}' }),
      step('show-result', { title: 'Converted', label: 'Converted Video' }),
    ],
  },
  {
    id: 86,
    name: 'Compress Image',
    icon: 'minimize-2',
    color: 'bg-green',
    category: 'media',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Image', buttonLabel: 'Select Image' }),
      step('set-var', { title: 'Save Image Path', varName: 'imgPath' }),
      step('user-input', {
        title: 'Compression Quality',
        label: 'Quality (1-100):',
        prefill: '75',
      }),
      step('image-compress', { filePath: '{{vars.imgPath}}', quality: '{{result}}' }),
      step('notification', { title: 'Image Compressed', body: 'File size reduced successfully.' }),
    ],
  },
]
