// System / Productivity shortcuts (ids 13–16, 28, 32–33, 37, 43–50, 53–54, 56, 58–59, 81)
import { makeStep, getActionDef } from '../actions/index.js'

function step(type, overrides = {}) {
  const def = getActionDef(type)
  if (!def) throw new Error(`defaultShortcuts: unknown action type "${type}"`)
  return { ...makeStep(def), ...overrides }
}

export default [
  {
    id: 13,
    name: 'Word Count',
    icon: 'hash',
    color: 'bg-cyan',
    category: 'personal',
    favorite: false,
    steps: [
      step('clipboard-read', { title: 'Read Clipboard' }),
      step('shell', {
        title: 'Count Words',
        command: "python3 -c \"\nimport sys\ntext = sys.stdin.read()\nwords = len(text.split())\nlines = text.count('\\n') + (1 if text and not text.endswith('\\n') else 0)\nchars = len(text)\nprint(f'Words: {words}\\nLines: {lines}\\nCharacters: {chars}')\n\" <<< '{{result}}'",
      }),
      step('show-result', { title: 'Text Stats', label: 'Text Statistics' }),
    ],
  },
  {
    id: 14,
    name: 'System Info',
    icon: 'cpu',
    color: 'bg-orange',
    category: 'personal',
    favorite: false,
    steps: [
      step('shell', {
        title: 'Gather System Info',
        command: 'echo "=== CPU ===" && grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | xargs && echo "" && echo "=== Memory ===" && free -h | awk \'/^Mem/{printf "Used: %s / Total: %s\\n", $3, $2}\' && echo "" && echo "=== Disk ===" && df -h / | awk \'NR==2{printf "Used: %s / Total: %s (%s used)\\n", $3, $2, $5}\' && echo "" && echo "=== Uptime ===" && uptime -p',
      }),
      step('show-result', { title: 'System Info', label: 'System Info' }),
    ],
  },
  {
    id: 15,
    name: 'Search Web',
    icon: 'search',
    color: 'bg-blue',
    category: 'personal',
    favorite: false,
    steps: [
      step('user-input', {
        title: 'Search Query',
        label: 'Search the web',
        placeholder: 'What are you looking for?',
      }),
      step('shell', {
        title: 'Build Search URL',
        command: "python3 -c \"import urllib.parse, sys; q = sys.stdin.read().strip(); print('https://www.google.com/search?q=' + urllib.parse.quote(q))\" <<< \"{{result}}\"",
      }),
      step('url-open', { title: 'Open Search', url: '{{result}}' }),
    ],
  },
  {
    id: 16,
    name: 'To Uppercase',
    icon: 'type',
    color: 'bg-green',
    category: 'personal',
    favorite: false,
    steps: [
      step('clipboard-read', { title: 'Read Clipboard' }),
      step('shell', {
        title: 'Convert to Uppercase',
        command: "echo \"{{result}}\" | tr '[:lower:]' '[:upper:]'",
      }),
      step('clipboard-write', { title: 'Copy Result' }),
    ],
  },
  {
    id: 28,
    name: 'Save Note to File',
    icon: 'file-down',
    color: 'bg-green',
    category: 'personal',
    favorite: false,
    steps: [
      step('user-input', {
        title: 'Note Content',
        label: 'Type your note',
        placeholder: 'Write anything here...',
      }),
      step('file-write', {
        title: 'Save File',
        path: '',
        content: '{{result}}',
      }),
      step('show-result', { title: 'Saved', label: 'Saved to File' }),
    ],
  },
  {
    id: 32,
    name: 'Open App',
    icon: 'rocket',
    color: 'bg-orange',
    category: 'personal',
    favorite: false,
    steps: [
      step('user-input', {
        title: 'App or File',
        label: 'App name, command, or file path',
        placeholder: 'gedit, vlc, /home/user/doc.pdf',
      }),
      step('app-launch', { title: 'Launch', target: '{{result}}' }),
    ],
  },
  {
    id: 33,
    name: 'AI from File',
    icon: 'sparkles',
    color: 'bg-purple',
    category: 'ai',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick Text File', buttonLabel: 'Select File' }),
      step('file-read', { title: 'Read File' }),
      step('set-var', { title: 'Save File Content', varName: 'fileContent' }),
      step('user-input', {
        title: 'Instruction',
        label: 'What should AI do with this file?',
        placeholder: 'Translate to French / Extract action items / ...',
      }),
      step('ai-prompt', {
        title: 'Process with AI',
        prompt: '{{result}}\n\n{{vars.fileContent}}',
        systemPrompt: 'You are a helpful assistant. Follow the user instruction precisely.',
      }),
      step('clipboard-write', { title: 'Copy Result' }),
      step('show-result', { title: 'AI Result', label: 'Result' }),
    ],
  },
  {
    id: 37,
    name: 'Rename File',
    icon: 'edit-3',
    color: 'bg-blue',
    category: 'personal',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Pick file to rename' }),
      step('set-var', { title: 'Save Old Path', varName: 'oldPath' }),
      step('user-input', {
        title: 'New Name',
        label: 'Enter new absolute path or filename:',
        prefill: '{{vars.oldPath}}',
      }),
      step('file-rename', { title: 'Rename', oldPath: '{{vars.oldPath}}', newPath: '{{result}}' }),
      step('notification', { title: 'Renamed', body: 'File renamed successfully' }),
    ],
  },
  {
    id: 43,
    name: 'Speed Test',
    icon: 'gauge',
    color: 'bg-blue',
    category: 'personal',
    favorite: false,
    steps: [
      step('shell', { title: 'Testing Speed...', command: 'speedtest-cli --simple || echo "speedtest-cli not found. Install with: sudo apt install speedtest-cli"' }),
      step('show-result', { title: 'Network Speed', label: 'Speed Test Results' }),
    ],
  },
  {
    id: 44,
    name: 'Weather Forecast',
    icon: 'cloud-sun',
    color: 'bg-cyan',
    category: 'personal',
    favorite: true,
    steps: [
      step('user-input', { title: 'Location', label: 'Enter City:', placeholder: 'Paris, London, New York...' }),
      step('shell', { title: 'Fetching Weather...', command: 'curl -s "wttr.in/{{result}}?nT0"' }),
      step('show-result', { title: 'Weather', label: 'Local Forecast' }),
    ],
  },
  {
    id: 45,
    name: 'Password Generator',
    icon: 'key',
    color: 'bg-purple',
    category: 'personal',
    favorite: false,
    steps: [
      step('shell', { title: 'Generating...', command: 'openssl rand -base64 12' }),
      step('clipboard-write', { title: 'Copy Password' }),
      step('show-result', { title: 'Generated Password', label: 'Secure Password (copied!)' }),
    ],
  },
  {
    id: 47,
    name: 'Optimize PDF',
    icon: 'file-down',
    color: 'bg-red',
    category: 'personal',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Select PDF', buttonLabel: 'Optimize This' }),
      step('set-var', { varName: 'oldPdf' }),
      step('shell', {
        title: 'Compressing...',
        command: 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile="{{vars.oldPdf}}.min.pdf" "{{vars.oldPdf}}"',
      }),
      step('notification', { title: 'PDF Optimized', body: 'Compressed version saved as .min.pdf' }),
    ],
  },
  {
    id: 48,
    name: 'Extract PDF Text',
    icon: 'file-text',
    color: 'bg-blue',
    category: 'personal',
    favorite: false,
    steps: [
      step('file-picker', { title: 'Select PDF' }),
      step('shell', { title: 'Extracting...', command: 'pdftotext "{{result}}" -' }),
      step('show-result', { title: 'Extracted Text', label: 'PDF Content' }),
    ],
  },
  {
    id: 49,
    name: 'Battery Health',
    icon: 'battery-medium',
    color: 'bg-green',
    category: 'personal',
    favorite: false,
    steps: [
      step('shell', {
        title: 'Checking...',
        command: 'upower -i $(upower -e | grep BAT) | grep -E "state|to\\ full|percentage|capacity"',
      }),
      step('show-result', { title: 'Battery Status', label: 'Power Info' }),
    ],
  },
  {
    id: 50,
    name: 'Smart Calculator',
    icon: 'calculator',
    color: 'bg-orange',
    category: 'personal',
    favorite: true,
    steps: [
      step('user-input', { title: 'Math Expression', label: 'Enter expression:', placeholder: 'sqrt(144) + 2^5' }),
      step('math-evaluate', { title: 'Calculating...', expression: '{{result}}' }),
      step('show-result', { title: 'Result', label: 'Calculation' }),
    ],
  },
  {
    id: 53,
    name: 'Is Site Down?',
    icon: 'globe',
    color: 'bg-red',
    category: 'personal',
    favorite: false,
    steps: [
      step('user-input', { title: 'URL', label: 'Check website:', placeholder: 'google.com' }),
      step('shell', { title: 'Checking...', command: 'curl -Is "{{result}}" | head -n 1' }),
      step('show-result', { title: 'Status', label: 'Server Response' }),
    ],
  },
  {
    id: 54,
    name: 'Explain Command',
    icon: 'help-circle',
    color: 'bg-purple',
    category: 'ai',
    favorite: false,
    steps: [
      step('clipboard-read', { title: 'Get Command' }),
      step('ai-prompt', {
        title: 'Explaining...',
        prompt: 'Explain what this shell command does in simple terms:\n\n`{{result}}`',
      }),
      step('show-result', { title: 'Explanation', label: 'How it works' }),
    ],
  },
  {
    id: 56,
    name: 'Find Large Files',
    icon: 'hard-drive',
    color: 'bg-orange',
    category: 'personal',
    favorite: false,
    steps: [
      step('folder-picker', { title: 'Select Directory' }),
      step('shell', { title: 'Searching...', command: 'du -ah "{{result}}" | sort -rh | head -n 20' }),
      step('show-result', { title: 'Largest Files', label: 'Top 20 space takers' }),
    ],
  },
  {
    id: 58,
    name: 'WiFi QR Code',
    icon: 'wifi',
    color: 'bg-blue',
    category: 'personal',
    favorite: false,
    steps: [
      step('user-input', { title: 'SSID', label: 'WiFi Name:', placeholder: 'Home-WiFi' }),
      step('set-var', { varName: 'ssid' }),
      step('user-input', { title: 'Password', label: 'WiFi Password:', placeholder: 'password123' }),
      step('qr-code', { title: 'Generating...', text: 'WIFI:S:{{vars.ssid}};T:WPA;P:{{result}};;' }),
      step('show-result', { title: 'WiFi Share', label: 'Scan to join {{vars.ssid}}' }),
    ],
  },
  {
    id: 59,
    name: 'Translate to FR',
    icon: 'languages',
    color: 'bg-blue',
    category: 'ai',
    favorite: false,
    steps: [
      step('clipboard-read'),
      step('ai-prompt', {
        title: 'Translating...',
        prompt: 'Translate the following to French:\n\n{{result}}',
        systemPrompt: 'Translate accurately and naturally. Reply only with the translation.',
      }),
      step('clipboard-write'),
      step('notification', { title: 'Translated', body: 'French version copied to clipboard' }),
    ],
  },
  {
    id: 81,
    name: 'Share to Tondro',
    icon: 'share-2',
    color: 'bg-blue',
    category: 'personal',
    favorite: true,
    steps: [
      step('file-picker', { title: 'Pick Files', buttonLabel: 'Share', multiple: true }),
      step('supabase-upload', { title: 'Uploading to Tondro...', bucket: 'tondro_app_uploads' }),
      step('set-var', { title: 'Save Content List', varName: 'contentNames' }),
      step('user-input', {
        title: 'Share Title',
        label: 'Enter a title for this share:',
        prefill: 'My shared files',
      }),
      step('set-var', { title: 'Save Title', varName: 'shareTitle' }),
      step('user-input', {
        title: 'Password protection',
        label: 'Enter a password (leave empty for none):',
        placeholder: 'password123',
        prefill: '',
      }),
      step('set-var', { title: 'Save Password', varName: 'sharePassword' }),
      step('shell', {
        title: 'Calculating Expiry',
        command: 'date -d "+1 month" --iso-8601=seconds',
      }),
      step('set-var', { title: 'Save Expiry', varName: 'expiresAt' }),
      step('supabase-rpc', {
        title: 'Creating Tondro Wave...',
        functionName: 'tondro_app.manage_share',
        params: '{"title_input": "{{vars.shareTitle}}", "type_input": "file", "content_input": "{{vars.contentNames}}", "password_input": "{{vars.sharePassword}}", "expires_at_input": "{{vars.expiresAt}}"}',
      }),
      step('json-extract', { title: 'Getting Slug', path: 'slug' }),
      step('set-var', { title: 'Save Slug', varName: 'shareSlug' }),
      step('shell', {
        title: 'Generating Link',
        command: 'echo "https://tondro.makix.fr/#view/{{vars.shareSlug}}"',
      }),
      step('clipboard-write', { title: 'Copy Link' }),
      step('show-result', { title: 'Tondro Link', label: 'Share Link' }),
    ],
  },
]
